version: '2'

services:

  vote:
    build: ./vote
    ports: 
      - 81:80
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    ports:
      - 80:80
    depends_on:
      - redis
      - db
  
  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
