version: '3'

services:

  vote:
    build: ./vote
    ports: 
      - 81:80
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier
    volumes:
      - vote-data:/app/data

  result:
    build: ./result
    ports:
      - 80:80
    depends_on:
      - redis
      - db
    networks:
      - front-tier
      - back-tier
    volumes:
      - result-data:/app/data


  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:alpine
    volumes: 
      - db-data:/var.lib/
    networks:
      - back-tier
    
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier
      
volumes:
  db-data:
  vote-data:
  result-data:

networks:
  front-tier:
  back-tier:


